name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.2]

    env:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
      POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
      DSGD_OWNER_PRIVATE_KEY: ${{ secrets.DSGD_OWNER_PRIVATE_KEY }}
      DMYR_OWNER_PRIVATE_KEY: ${{ secrets.DMYR_OWNER_PRIVATE_KEY }}
      MCBDC_OWNER_PRIVATE_KEY: ${{ secrets.MCBDC_OWNER_PRIVATE_KEY }}
      VOUCHER_OWNER_PRIVATE_KEY: ${{ secrets.VOUCHER_OWNER_PRIVATE_KEY }}
      ECOMMERCE_OWNER_PRIVATE_KEY: ${{ secrets.ECOMMERCE_OWNER_PRIVATE_KEY }}
      DSGDTOKEN_CONTRACT_ADDRESS: ${{ secrets.DSGDTOKEN_CONTRACT_ADDRESS }}
      DMYRTOKEN_CONTRACT_ADDRESS: ${{ secrets.DMYRTOKEN_CONTRACT_ADDRESS }}
      MCBDC_CONTRACT_ADDRESS: ${{ secrets.MCBDC_CONTRACT_ADDRESS }}
      VOUCHER_CONTRACT_ADDRESS: ${{ secrets.VOUCHER_CONTRACT_ADDRESS }}
      ECOMMERCE_CONTRACT_ADDRESS: ${{ secrets.ECOMMERCE_CONTRACT_ADDRESS }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: |
        echo "Installing dependencies..."
        npm install

    - name: Compile Smart Contracts
      run: |
        echo "Compiling smart contracts..."
        npx hardhat clean
        npx hardhat compile

    - name: Save Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compiled-contracts
        path: |
          artifacts
          cache/*.json

    - name: Get build artifacts
      uses: actions/download-artifact@v3
      with:
        name: compiled-contracts

    - name: List files in the artifacts directory
      run: |
        echo "Listing files in the artifacts directory..."
        ls -R artifacts

    - name: Run Tests
      run: |
        echo "Running tests..."
        npm run test

    - name: Deploy API
      run: |
        echo "Deploying API..."
        npm run start
      env:
        ALCHEMY_API_KEY: ${{ env.ALCHEMY_API_KEY }}
        POLYGON_RPC_URL: ${{ env.POLYGON_RPC_URL }}
        POLYGONSCAN_API_KEY: ${{ env.POLYGONSCAN_API_KEY }}
        DSGD_OWNER_PRIVATE_KEY: ${{ env.DSGD_OWNER_PRIVATE_KEY }}
        DMYR_OWNER_PRIVATE_KEY: ${{ env.DMYR_OWNER_PRIVATE_KEY }}
        MCBDC_OWNER_PRIVATE_KEY: ${{ env.MCBDC_OWNER_PRIVATE_KEY }}
        VOUCHER_OWNER_PRIVATE_KEY: ${{ env.VOUCHER_OWNER_PRIVATE_KEY }}
        ECOMMERCE_OWNER_PRIVATE_KEY: ${{ env.ECOMMERCE_OWNER_PRIVATE_KEY }}
        DSGDTOKEN_CONTRACT_ADDRESS: ${{ env.DSGDTOKEN_CONTRACT_ADDRESS }}
        DMYRTOKEN_CONTRACT_ADDRESS: ${{ env.DMYRTOKEN_CONTRACT_ADDRESS }}
        MCBDC_CONTRACT_ADDRESS: ${{ env.MCBDC_CONTRACT_ADDRESS }}
        VOUCHER_CONTRACT_ADDRESS: ${{ env.VOUCHER_CONTRACT_ADDRESS }}
        ECOMMERCE_CONTRACT_ADDRESS: ${{ env.ECOMMERCE_CONTRACT_ADDRESS }}
